update hooks

diff --git a/scripts/git_hooks/pre-commit b/scripts/git_hooks/pre-commit
--- a/scripts/git_hooks/pre-commit
+++ b/scripts/git_hooks/pre-commit
@@ -1,59 +1,62 @@
 #!/bin/bash
 
 error() {
-    echo -e "\e[1m\e[31m$1\e[0m"
+  echo -e "\e[1m\e[31m$1\e[0m"
 }
 
 section() {
-    echo -e "\e[33m[\e[32m\e[1m $1 \e[21m\e[33m]\e[0m"
+  echo -e "\e[33m[\e[32m\e[1m $1 \e[21m\e[33m]\e[0m"
 }
 
 lint() {
-    PROJECT=$1
-    STAGED_FILES=$2
+  PROJECT=$1
+  STAGED_FILES=$2
 
-    section "start php lint"
+  section "start php lint"
+  echo ""
 
-    for FILE in ${STAGED_FILES}; do
-        php -l -d display_errors=0 "${PROJECT}"/"${FILE}"
+  for FILE in ${STAGED_FILES}; do
+    php -l -d display_errors=0 "${PROJECT}"/"${FILE}"
 
-        if [[ $? != 0 ]]; then
-            error "fix the error before commit"
-            stop 1
-        fi
-    done
+    if [[ $? != 0 ]]; then
+      error "fix the error before commit"
+      stop 1
+    fi
+  done
 
-    section "end php lint"
+  echo ""
+  section "end php lint"
 }
 
 code_sniffer() {
-    STAGED_FILES=$1
+  STAGED_FILES=$1
 
-    section "start code sniffer"
+  section "start code sniffer"
+  echo ""
 
-    ./vendor/bin/phpcs --encoding=utf-8 -n -p --colors ${STAGED_FILES}
+  ./vendor/bin/phpcs --no-cache --encoding=utf-8 -n -p -v -s ${STAGED_FILES}
 
-    if [[ $? != 0 ]]; then
-        error "fix the following errors before commit"
-        stop 1
-    fi
+  if [[ $? != 0 ]]; then
+    error "fix the following errors before commit"
+    stop 1
+  fi
 
-    section "end code sniffer"
+  section "end code sniffer"
 }
 
 check_php() {
-    php -v > /dev/null 2>&1
-    PHP_IS_INSTALLED=$?
+  php -v >/dev/null 2>&1
+  PHP_IS_INSTALLED=$?
 
-    if [[ "${PHP_IS_INSTALLED}" -ne 0 ]]; then
-        error "php is not installed"
-        stop 0
-    fi
+  if [[ "${PHP_IS_INSTALLED}" -ne 0 ]]; then
+    error "php is not installed"
+    stop 0
+  fi
 }
 
 stop() {
-    section "stop pre commit hook"
-    exit $1
+  section "stop pre commit hook"
+  exit $1
 }
 
 PROJECT="${PWD}"
@@ -61,7 +64,7 @@ STAGED_FILES_CMD=$(git diff --cached --name-only --diff-filter=ACMR HEAD | grep 
 
 # determine if a file list is passed
 if [[ "$#" -eq 1 ]]; then
-    STAGED_FILES="$1"
+  STAGED_FILES="$1"
 fi
 STAGED_FILES=${STAGED_FILES:-$STAGED_FILES_CMD}
 
@@ -70,11 +73,11 @@ section "${PROJECT} start pre commit hook"
 check_php
 
 if [[ "${STAGED_FILES}" != "" ]]; then
-    lint "${PROJECT}" "${STAGED_FILES}"
+  lint "${PROJECT}" "${STAGED_FILES}"
 
-    echo ""
+  echo ""
 
-    code_sniffer "${STAGED_FILES}"
+  code_sniffer "${STAGED_FILES}"
 fi
 
 stop $?
